movie/urls.py
from django.contrib import admin
from django.urls import path
from movie import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.home, name='home'),
                  path('movie/', views.movie, name='movie'),
                  path('Series/', views.Series, name='Series'),
                  path('moviedetail/<int:id>/', views.moviedetail, name='moviedetail'),
                  path('seriesdetail/<int:id>/', views.seriesdetail, name='seriesdetail'),
                  path('search/', views.search, name='search'),
                  path('Subscribe/', views.Subscribe, name='Subscribe'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movie.urls")),
]

movie/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.db.models.fields import CharField
from django.utils.translation import gettext_lazy as _


# Create your models here.
class category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class session(models.Model):
    Name =(
        ('Latest Movies', "Latest Movies"),
        ("Web-series", "Web-series"),
    )
    name = models.CharField(choices=Name,max_length=100)

    def __str__(self):
        return self.name


class movie(models.Model):
    name = models.CharField(max_length=250)
    poster = models.ImageField(upload_to="movie/poster/image/")
    description = RichTextField()
    category = models.ForeignKey(category, on_delete=models.CASCADE)
    Releaseyear = models.IntegerField()
    Downloadlink = models.URLField()
    watchtralier = models.URLField()
    IMDB_rating = models.FloatField()
    current_season = models.CharField(max_length=250)
    detail = models.CharField(max_length=250)
    episode = models.CharField(max_length=250)
    session = models.ForeignKey(session,on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name


class All_season(models.Model):
    movie = models.ForeignKey(movie, on_delete=models.CASCADE)
    All_season = models.CharField(max_length=250)
    detail = models.CharField(max_length=250)
    episode = models.CharField(max_length=250)
    link = models.CharField(max_length=500)
    poster = models.CharField(max_length=250)



class media(models.Model):
    movie = models.ForeignKey(movie, on_delete=models.CASCADE)
    photo = models.CharField(max_length=250)


class Genres(models.Model):
    movie = models.ForeignKey(movie, on_delete=models.CASCADE)
    genre = (
        ('Action', "Action"),
        ("Thriller", "Thriller"),
        ("Horror", "Horror"),
        ("Drama", "Drama"),
        ("Romance", "Romance"),
        ("Sci-fi", "Sci-fi"),
        ("Crime film", "Crime film"),
        ("War", "War"),
        ("Westerns", "Westerns"),
        ("COMEDY", "COMEDY"),
        ("Sports", "Sports"),
        ("Adventure", "Adventure"),
        ("Documentary", "Documentary"),
        ("Romantic comedy", "Romantic comedy"),
        ("Fiction", "Fiction"),
        ("Mystery", "Mystery"),
        ("Epic", "Epic"),
        ("Dark comedy", "Dark comedy"),
        ("Experimental", "Experimental"),
        ("Animated film", "Animated film"),
        ("Sports", "Sports"),
        ("web-series", "web-series"),
        ("Biographical", "Biographical"),
        ("Disaster", "Disaster"),
        ("Coming-of-age story", "Coming-of-age story"),
        ("cartoon", "cartoon"),
        ("Anime", "Anime"),
        ("Road", "Road"),
        ("Spy", "Spy"),
        ("Silent", "Silent"),
        ("Propaganda", "Propaganda"),
        ("Dance film", "Dance film")

    )
    genres = models.CharField(choices=genre, max_length=100)
    color = models.CharField(max_length=100)





class keyword(models.Model):
    movie = models.ForeignKey(movie, on_delete=models.CASCADE)
    keyword = models.CharField(max_length=100)

class downloadlink(models.Model):
    movie = models.ForeignKey(movie, on_delete=models.CASCADE)
    link = models.URLField()
    title = models.CharField(max_length=250)
    size = models.CharField(max_length=250)

class subscribe(models.Model):
    email1 = models.EmailField()

templates/base.html
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie ie7 no-js" lang="en-US">
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8 no-js" lang="en-US">
<![endif]-->
<!--[if !(IE 7) | !(IE 8)  ]><!-->
<html lang="en" class="no-js">
{% load static %}

<head>
	<!-- Basic need -->
	<title>MOVIE POINT</title>
	<meta charset="UTF-8">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="">
	<link rel="profile" href="#">

    <!--Google Font-->
    <link rel="stylesheet" href='http://fonts.googleapis.com/css?family=Dosis:400,700,500|Nunito:300,400,600' />
	<!-- Mobile specific meta -->
	<meta name=viewport content="width=device-width, initial-scale=1">
	<meta name="format-detection" content="telephone-no">
	    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico'%}">

	<!-- CSS files -->
	<link rel="stylesheet" href="{% static 'css/plugins.css'%}">
	<link rel="stylesheet" href="{% static 'css/style.css'%}">

</head>
<body>
<!--preloading-->
<div id="preloader">
    <img class="logo" src="{% static 'images/logo.png'%}" alt="" width="119" height="58">
    <div id="status">
        <span></span>
        <span></span>
    </div>
</div>
<!--end of preloading-->
 {%block content%}
    {%endblock%}

<script src="{% static 'js/jquery.js'%}"></script>
<script src="{% static 'js/plugins.js'%}"></script>
<script src="{% static 'js/plugins2.js'%}"></script>
<script src="{% static 'js/custom.js'%}"></script>

</body>


</html>

templates/footer.html
{% load static %}
<footer class="ht-footer">
	<div class="container">
		<div class="flex-parent-ft">
			<div class="flex-child-ft item1">
				 <a href="{% url 'home'%}"><img class="logo" src="{% static 'images/logo1.png'%}" alt=""></a>
				 <p>5th Avenue st, manhattan<br>
				New York, NY 10001</p>
				<p>Call us: <a href="#">(+01) 202 342 6789</a></p>
			</div>
			<div class="flex-child-ft item5">
				<h4>Newsletter</h4>
				<p>Subscribe to our newsletter system now <br> to get latest news from us.</p>
				    <form action="{% url 'Subscribe'%}" method="post">
                            {% csrf_token %}
                            <input type="email" placeholder="Enter your email here..." name="email1">
                            <button type="submit">subscribe</button>
                        </form>
			</div>
		</div>
	</div>
	<div class="ft-copyright">
		<div class="ft-left">
			<p><a target="_blank" ></a></p>
		</div>
		<div class="backtotop">
			<p><a href="#" id="back-to-top">Back to top  <i class="ion-ios-arrow-thin-up"></i></a></p>
		</div>
	</div>
</footer>

templates/header.html
{% load static %}
<header class="ht-header">
    <div class="container">
        <nav class="navbar navbar-default navbar-custom">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header logo">
                <div class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <div id="nav-icon1">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
                <a href="{% url 'home' %}"><img class="logo" src="{% static 'images/logo.png'%}" alt="" width="119"
                                                height="58"></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse flex-parent" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav flex-child-menu menu-left">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="dropdown first">
                        <a class="btn btn-default dropdown-toggle lv1" href="{% url 'home' %}">
                            Home
                        </a>
                    </li>
                    <li class="dropdown first">
                        <a class="btn btn-default dropdown-toggle lv1" href="{% url 'movie' %}">
                            movies
                        </a>
                    </li>
                    <li class="dropdown first">
                        <a class="btn btn-default dropdown-toggle lv1" href="{% url 'Series' %}">
                            web-series
                        </a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <!-- top search form -->
        <div class="top-search">
            <select hidden="hidden">
                {% for i in cat %}
                <option value="i.id" >{{i.name}}</option>
                {% endfor %}
            </select>
            <form action="{% url 'search' %}" method="get">
                <input type="text" placeholder="Search for a movie, TV Show or celebrity that you are looking for" name="query" id="query" style="margin-right: 725px;">
            </form>
        </div>
    </div>
</header>

templates/home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!-- BEGIN | Header -->
{% include 'header.html' %}
<!-- END | Header -->
<div class="slider movie-items">
    <div class="container">
        <div class="row">
            <div class="slick-multiItemSlider">
                {% for i in films %}
                <div class="movie-item">
                    <div class="mv-img">
                        <a href="{% url 'moviedetail' i.id %}"><img src="{{i.poster.url}}" alt="" width="285"
                                                                    height="437"></a>
                    </div>
                    <div class="title-in">
                        <div class="cate">
                            {% for i1 in i.genres_set.all %}
                            <span class="{{i1.color}}"><a href="#">{{i1.genres}}</a></span>
                            {% endfor %}
                        </div>
                        <h6><a href="{% url 'moviedetail' i.id %}">{{i.name}}</a></h6>
                        <p><i class="ion-android-star"></i><span>{{i.IMDB_rating}}</span> /10</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div class="movie-items">
    <div class="container">
        <div class="row ipad-width">
            <div class="col-md-12">
                <div class="title-hd">
                    <h2>Latest Movies</h2>
                    <a href="{% url 'movie'%}" class="viewall">View all <i class="ion-ios-arrow-right"></i></a>
                </div>
                <div class="tabs">
                    <div class="tab-content">
                        <div id="tab1-h2" class="tab active">
                            <div class="row">
                                <div class="slick-multiItem2">
                                    {% for i in film %}
                                    <div class="slide-it">
                                        <div class="movie-item">
                                            <div class="mv-img">
                                                <img src="{{i.poster.url}}" alt="" width="185" height="284">
                                            </div>
                                            <div class="hvr-inner">
                                                <a href="{% url 'moviedetail' i.id  %}"> Read more <i
                                                        class="ion-android-arrow-dropright"></i> </a>
                                            </div>
                                            <div class="title-in">
                                                <h6><a href="{% url 'moviedetail' i.id %}">{{i.name}}</a></h6>
                                                <p><i class="ion-android-star"></i><span>{{i.IMDB_rating}}</span> /10
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="title-hd">
                    <h2>web-series</h2>
                    <a href="{% url 'Series'%}" class="viewall">View all <i class="ion-ios-arrow-right"></i></a>
                </div>
                <div class="tabs">
                    <div class="tab-content">
                        <div id="tab1-h2" class="tab active">
                            <div class="row">
                                <div class="slick-multiItem2">
                                    {% for i3 in Serie %}
                                    <div class="slide-it">
                                        <div class="movie-item">
                                            <div class="mv-img">
                                                <img src="{{i3.poster.url}}" alt="" width="185" height="284">
                                            </div>
                                            <div class="hvr-inner">
                                                <a href="{% url 'seriesdetail' i3.id  %}"> Read more <i
                                                        class="ion-android-arrow-dropright"></i> </a>
                                            </div>
                                            <div class="title-in">
                                                <h6><a href="{% url 'seriesdetail' i3.id %}">{{i3.name}}</a></h6>
                                                <p><i class="ion-android-star"></i><span>{{i3.IMDB_rating}}</span> /10
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- footer section-->
{% include 'footer.html' %}
<!-- end of footer section-->
{% endblock %}

templates/moviesingle.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!-- BEGIN | Header -->
{% include 'header.html' %}
<!-- END | Header -->


<div class="hero mv-single-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
            </div>
        </div>
    </div>
</div>
<div class="page-single movie-single movie_single">
    <div class="container">
        <div class="row ipad-width2">
            <div class="col-md-4 col-sm-12 col-xs-12">
                <div class="movie-img sticky-sb">
                    <img src="{{film.poster.url}}" alt="">
                    <div class="movie-btn">
                        <div class="btn-transform transform-vertical red">
                            <div><a href="#" class="item item-1 redbtn"> <i class="ion-play"></i> Watch Trailer</a>
                            </div>
                            <div><a href="{{film.watchtralier}}" class="item item-2 redbtn "><i
                                    class="ion-play"></i></a></div>
                        </div>
                        <div class="btn-transform transform-vertical">
                            <div><a href="#" class="item item-1 yellowbtn"> <i class="fa fa-download"></i>Download</a>
                            </div>
                            <div><a href="{{film.Downloadlink}}" class="item item-2 yellowbtn"><i
                                    class="fa fa-download"></i></a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8 col-sm-12 col-xs-12">
                <div class="movie-single-ct main-content">
                    <h1 class="bd-hd">{{film.name}} <span>{{film.Releaseyear}}</span></h1>
                    <div class="film-rate">
                        <div class="rate">
                            <p><i class="ion-android-star"> IMDB RATING</i></p>
                            <p><span>{{film.IMDB_rating}}</span> /10<br>
                            </p>
                        </div>
                    </div>
                    <div class="movie-tabs">
                        <div class="tabs">
                            <ul class="tab-links tabs-mv">
                                <li class="active"><a href="#overview">Overview</a></li>
                                <li><a href="#media"> Media</a></li>
                            </ul>
                            <div class="tab-content">
                                <div id="overview" class="tab active">
                                    <div class="row">
                                        <div class="col-md-8 col-sm-12 col-xs-12">
                                            <p> {{film.description}} </p>
                                            <div class="title-hd-sm">
                                                <h4>Photos</h4>
                                                <a href="#media" class="time">All{{data2}} Photos <i
                                                        class="ion-ios-arrow-right"></i></a>
                                            </div>
                                            {% for i3 in film.media_set.all %}
                                            <div class="mvsingle-item ov-item">
                                                <a class="img-lightbox" data-fancybox-group="gallery"
                                                   href="{{i3.photo}}"><img src="{{i3.photo}}" alt="" style=" width: 20%;"></a>
                                            </div>
                                            {% endfor %}
                                            <div class="title-hd-sm">
                                                <h4>Download link</h4>
                                            </div>
                                            <!-- movie cast -->
                                            <div class="mvcast-item">
                                                <div class="cast-it">
                                                    {% for i4 in film.downloadlink_set.all %}
                                                    <div class="cast-left">
                                                        <a href="{{i4.link}}">{{i4.title}}</a>
                                                    </div>
                                                    <p>... ({{i4.size}})</p>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-4 col-xs-12 col-sm-12">
                                            <div class="sb-it">
                                                <h6>Plot Keywords:</h6>
                                                <p class="tags">
                                                    {% for i2 in film.Keyword_set.all %}
                                                    <span class="time"><a href="#">{{i2.keyword}}</a></span>
                                                    {% endfor %}
                                                </p>
                                            </div>
                                            <div class="ads">
                                                <img src="images/uploads/ads1.png" alt="">
                                            </div>

                                        </div>
                                    </div>
                                </div>
                                <div id="media" class="tab">
                                    <div class="row">
                                        <div class="rv-hd">
                                            <div>
                                                <h3> Photos </h3>
                                                <h2>{{film.name}}</h2>
                                            </div>
                                        </div>
                                        <div class="title-hd-sm">
                                            <h4>Photos <span> ({{data2}})</span></h4>
                                        </div>
                                        {% for i3 in film.media_set.all %}
                                        <div class="mvsingle-item">

                                            <a class="img-lightbox" data-fancybox-group="gallery"
                                               href="{{i3.photo}}"><img src="{{i3.photo}}" alt="" style=" width: 20%;"></a>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- footer section-->
{% include 'footer.html' %}
<!-- end of footer section-->
{% endblock %}

templates/seriessingle.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!-- BEGIN | Header -->
{% include 'header.html' %}
<!-- END | Header -->

<div class="hero sr-single-hero sr-single">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <!-- <h1> movie listing - list</h1>
                <ul class="breadcumb">
                    <li class="active"><a href="#">Home</a></li>
                    <li> <span class="ion-ios-arrow-right"></span> movie listing</li>
                </ul> -->
            </div>
        </div>
    </div>
</div>
<div class="page-single movie-single movie_single">
    <div class="container">
        <div class="row ipad-width2">
            <div class="col-md-4 col-sm-12 col-xs-12">
                <div class="movie-img sticky-sb">
                    <img src="{{serie.poster.url}}" alt="" style="">
                    <div class="movie-btn">
                        <div class="btn-transform transform-vertical red">
                            <div><a href="{{serie.watchtralier}}" class="item item-1 redbtn"> <i class="ion-play"></i>
                                Watch Trailer</a>
                            </div>
                            <div><a href="{{serie.watchtralier}}"
                                    class="item item-2 redbtn fancybox-media hvr-grow"><i class="ion-play"></i></a>
                            </div>
                        </div>
                        <div class="btn-transform transform-vertical">
                            <div><a href="{{serie.watchtralier}}" class="item item-1 yellowbtn"> <i
                                    class="fa fa-download"></i> Download</a>
                            </div>
                            <div><a href="{{serie.watchtralier}}" class="item item-2 yellowbtn"><i
                                    class="fa fa-download"></i></a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8 col-sm-12 col-xs-12">
                <div class="movie-single-ct main-content">
                    <h1 class="bd-hd">{{serie.name}} <span> {{Releaseyear}}</span></h1>
                    <div class="movie-rate">
                        <div class="rate">
                            <i class="ion-android-star">IMDB RATING</i>
                            <p><span>{{serie.IMDB_rating}}</span> /10<br>
                            </p>
                        </div>
                    </div>
                    <div class="movie-tabs">
                        <div class="tabs">
                            <ul class="tab-links tabs-mv tabs-series">
                                <li class="active"><a href="#overview">Overview</a></li>
                                <li><a href="#media"> Media</a></li>
                                <li><a href="#season"> Season</a></li>

                            </ul>
                            <div class="tab-content">
                                <div id="overview" class="tab active">
                                    <div class="row">
                                        <div class="col-md-8 col-sm-12 col-xs-12">
                                            <p></p>
                                            <div class="title-hd-sm">
                                                <h4>Current Season</h4>
                                            </div>
                                            <!-- movie cast -->
                                            <div class="mvcast-item">
                                                <div class="cast-it">
                                                    <div class="cast-left series-it">
                                                        <img src="{{serie.poster.url}}" alt="" style=" width: 20%;">
                                                        <div>
                                                            <a href="#">Season {{serie.current_season}}</a>
                                                            <p>{{serie.episode}} Episodes</p>
                                                            <p>{{serie.detail}}</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <!-- movie cast -->
                                            <div class="title-hd-sm">
                                                <h4>Download link</h4>
                                            </div>
                                            <!-- movie cast -->
                                            <div class="mvcast-item">
                                                <div class="cast-it">
                                                    {% for i4 in serie.episode_series_set.all %}
                                                    <div class="cast-left">
                                                        <a href="{{i4.link}}">{{i4.title}}</a>
                                                    </div>
                                                    <p>... ({{i4.size}})</p>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="media" class="tab">
                                    <div class="row">
                                        <div class="rv-hd">
                                            <div>
                                                <h3>Photos of</h3>
                                                <h2>{{serie.name}}</h2>
                                            </div>
                                        </div>
                                        <div class="title-hd-sm">
                                            <h4>Photos <span> ({{data2}})</span></h4>
                                        </div>
                                        <div class="mvsingle-item">
                                            {% for i in serie.media_set.all %}
                                            <a class="img-lightbox" data-fancybox-group="gallery"
                                               href="{{i.photo}}"><img src="{{i.photo}}"
                                                                       alt="" style=" width: 20%;"></a>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                                <div id="season" class="tab">
                                    <div class="row">
                                        <div class="mvcast-item">

                                            <div class="cast-it">
                                                {% for i2 in serie.All_season_set.all%}

                                                <div class="cast-left series-it">

                                                    <img src="{{i2.poster}}" alt="" style=" width: 20%;">
                                                    <div>
                                                        <a href="{{i2.link}}">Season {{i2.All_season}}</a>
                                                        <p>{{i2.episode}} Episodes</p>
                                                        <p>{{i2.detail}}</p>
                                                    </div>

                                                </div>
                                                {% endfor %}
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- footer section-->
{% include 'footer.html' %}
<!-- end of footer section-->
{% endblock %}